### ISSUE TITLE
spatstat.random would not install

### ISSUE THREAD

**Issue by sergeyfridrikh** [spatstat/spatstat.random#1]
I tried installing spatstat.random from R studio (R 4.2.2). The error message is below.

> install.packages('spatstat.random')
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/spatstat.random_3.1-5.tgz'
Warning in install.packages :
  downloaded length 0 != reported length 326
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/spatstat.random_3.1-5.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/spatstat.random_3.1-5.tgz'
Warning in install.packages :
  download of package ‘spatstat.random’ failed

**Comment by rubak** [comment]
I think the cran.rstudio.com mirror of CRAN must be out of sync. Try using e.g. the 0-cloud mirror instead (unfortunately I cannot test it as I'm not on mac):

```r
install.packages("spatstat.random", repos="https://cloud.r-project.org/")
```

**EDIT:**

Maybe just specifying `cran.r-project.org` works better if it is a matter of changes not propagating to mirrors yet. I don't know, but you could try:


```r
install.packages("spatstat.random", repos="https://cran.r-project.org/")
```

Alternatively you can update to R 4.3 and see if that helps or simply wait the problem out. My guess is that it solves itself within some days.

**Comment by sergeyfridrikh** [comment]
Thank you. At the end of the day the only thing that worked was reinstalling the newest version of R (4.3) & R studio.
