### ISSUE TITLE
unexpected output from simulating Gaussian random field with circulant embedding

### ISSUE THREAD

**Issue by jalilian** [spatstat/spatstat.random#3]
Dear spatstat team, thank you very much for the great work and efforts.

The implemented circulant embedding algorithm for simulating Gaussian random fields in the file ```randomcircembed.R``` appears sensitive to the dimension of the discrete (pixel image) approximation of the given window ```W```. The following code shows this point.
```
require(spatstat)
Z1 <- rGRFmatern(W=owin(), mu=0, var=1, scale=0.1, nu=1, dimyx=c(128, 128))
Z2 <- rGRFmatern(W=owin(), mu=0, var=1, scale=0.1, nu=1, dimyx=c(130, 126))
Z3 <- rGRFmatern(W=owin(), mu=0, var=1, scale=0.1, nu=1, dimyx=c(110, 220))
Z4 <- rGRFmatern(W=owin(), mu=0, var=1, scale=0.1, nu=1, dimyx=c(220, 110))

par(mfcol=c(2, 4))
plot(Z1)
image(Z1$v)
plot(Z2)
image(Z2$v)
plot(Z3)
image(Z3$v)
plot(Z4)
image(Z4$v)
```
As you can see, the generated fields ```Z2``` and ```Z3``` have a significantly different behaviour compared to ```Z1``` and ```Z4```.  I hope this example clarifies the issue. I could not find any reason for such an impact for the dimension of the pixel image in ```rCircEmbedEngine``` function.

**Comment by baddstats** [comment]
Thank you for drawing our attention to this. It is a bug in the matrix indexing.
I have fixed it in the development version `spatstat.random 3.2-3.002`.

**Comment by jalilian** [comment]
Thank you very much. The issue is resolved.
